In [1]:
"""
- 와인데이터 읽어들이기 : 변수명 wine
- 독립변수 : data와 종속변수 : target으로 분리하기
- 훈련 및 테스트 = 8 : 2로 분류하기(변수는 train_input, train_target, test_input, test_target으로)
- 정규화 하기 : ss 클래스명, 훈련데이터 정규화변수는 train_std_scaler, 테스트데이터는 test_std_scaler로 정규화
- 랜덤포레스트 모델로 분류하기 : 모델 변수명은 rf 사용(cpu core 갯수는 전체사용, 랜덤규칙 42 사용)
- 훈련시키기
"""

'\n- 와인데이터 읽어들이기 : 변수명 wine\n- 독립변수 : data와 종속변수 : target으로 분리하기\n- 훈련 및 테스트 = 8 : 2로 분류하기(변수는 train_input, train_target, test_input, test_target으로)\n- 정규화 하기 : ss 클래스명, 훈련데이터 정규화변수는 train_std_scaler, 테스트데이터는 test_std_scaler로 정규화\n- 랜덤포레스트 모델로 분류하기 : 모델 변수명은 rf 사용(cpu core 갯수는 전체사용, 랜덤규칙 42 사용)\n- 훈련시키기\n'

In [2]:
import pandas as pd

file_path = "./data/08_wine.csv"
wine = pd.read_csv(file_path)
wine

alcohol  sugar    pH  class
0         9.4    1.9  3.51    0.0
1         9.8    2.6  3.20    0.0
2         9.8    2.3  3.26    0.0
3         9.8    1.9  3.16    0.0
4         9.4    1.9  3.51    0.0
...       ...    ...   ...    ...
6492     11.2    1.6  3.27    1.0
6493      9.6    8.0  3.15    1.0
6494      9.4    1.2  2.99    1.0
6495     12.8    1.1  3.34    1.0
6496     11.8    0.8  3.26    1.0

[6497 rows x 4 columns]

In [3]:
import numpy as np
data = wine.iloc[:, :-1].to_numpy()
print(data.shape)

target = wine["class"].to_numpy()
print(target.shape)

(6497, 3)
(6497,)


In [4]:
### 훈련 : 테스트 = 8 : 2로 분류하기
# 변수명 : train_input, train_target, test_input, test_target 사용
from sklearn.model_selection import train_test_split

train_input, test_input, train_target, test_target = train_test_split(data, target, test_size=0.2, random_state=42)

print(f"{train_input.shape}, {test_input.shape}, {train_target.shape}, {test_target.shape}")

(5197, 3), (1300, 3), (5197,), (1300,)


In [5]:
from sklearn.preprocessing import StandardScaler

ss = StandardScaler()
ss.fit(data)

train_std_scaler = ss.transform(train_input)
test_std_scaler = ss.transform(test_input)

print(f"train_std_scaler = {train_std_scaler}\n test_std_scaler = {test_std_scaler}")

train_std_scaler = [[ 0.00687492  0.47436559 -0.17727182]
 [ 1.60000607 -0.70273867  0.25811972]
 [ 1.09691202 -0.70273867  1.19110159]
 ...
 [-0.83161516  0.03295149  0.13372214]
 [-0.83161516  0.53742474 -0.23947061]
 [-0.83161516 -0.57662035  1.81308951]]
 test_std_scaler = [[ 1.43230805  1.54637124  0.25811972]
 [-0.49621913 -0.68171895  0.32031851]
 [ 1.26461004  0.41130643 -0.23947061]
 ...
 [ 1.60000607 -0.76579782 -0.17727182]
 [-0.91546416  0.89475996  0.50691489]
 [-1.50240722  2.11390365 -1.98103678]]


In [6]:
from sklearn.ensemble import RandomForestClassifier

In [7]:
rf = RandomForestClassifier(n_jobs=-1, random_state=42)
rf

RandomForestClassifier(n_jobs=-1, random_state=42)

In [8]:
rf.fit(train_input, train_target)

RandomForestClassifier(n_jobs=-1, random_state=42)

In [9]:
"""
훈련모델 저장 및 불러오는 방법 2가지
- joblib
- pickle
"""

'\n훈련모델 저장 및 불러오는 방법 2가지\n- joblib\n- pickle\n'

In [10]:
### joblib 방식

In [11]:
### joblib 라이브러리
import joblib

In [12]:
### 훈련 모델 저장하기
# 저장할 위치 및 파일명 정의 : 확장자는 임의로 넣어도 됩니다.
#  (보통 방식에서는 확장자 를 주로 사용합니다.)
save_path = "./model/rf_model_joblib.md"

# 모델 저장시키기
joblib.dump(rf, save_path)

['./model/rf_model_joblib.md']

In [13]:
### 저장된 훈련모델 파일 불러들이기
rf_model = joblib.load(save_path)
rf_model

RandomForestClassifier(n_jobs=-1, random_state=42)

In [14]:
### 예측하기
rf_model.predict(test_input)

array([1., 0., 1., ..., 1., 1., 1.])

In [15]:
### pickle 방식

In [16]:
### pickle 라이브러리
import pickle

In [17]:
### 모델 저장하기
save_path = "./model/rf_model_pickle.md"

### wb : w는 파일쓰기 옵션, b는 바이너리 형식 -> 바이너리 형식으로 파일에 쓰기
# pickle방식은 파일을 열어서 쓰는 방식으로 저장됩니다.
with open(save_path, "wb") as fw :
    pickle.dump(rf, fw)

In [18]:
### 저장된 모델파일 읽어들이기
with open(save_path, "rb") as f :
    rf_model2 = pickle.load(f)

rf_model2

RandomForestClassifier(n_jobs=-1, random_state=42)

In [19]:
### 예측하기
rf_model2.predict(test_input)

array([1., 0., 1., ..., 1., 1., 1.])

In [20]:
test_input

array([[12.2 , 12.8 ,  3.26],
       [ 9.9 ,  2.2 ,  3.27],
       [12.  ,  7.4 ,  3.18],
       ...,
       [12.4 ,  1.8 ,  3.19],
       [ 9.4 ,  9.7 ,  3.3 ],
       [ 8.7 , 15.5 ,  2.9 ]])

In [21]:
rf_model2.predict([[12.2 , 12.8 ,  3.26]])

array([1.])